spring:
  datasource:
    url: jdbc:mysql://192.168.122.99:3306/springblog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.122.99
    port: 6380
    password: cislc